### ISSUE TITLE
Issues with Game Restart

### ISSUE THREAD

**Issue by sekharp** [amcrawford/game-time#16]
Hey Steve! Amber and I are close to having the game end when the snake hits the wall, but we can't seem to restart properly. The canvas clears after the alert when the snake hits the wall, but when we click the start button it doesn't start again. We suspect there might be an issue with start having already been clicked once, but we can't figure out where that's stored. Any thoughts? @stevekinney

**Comment by sekharp** [comment]
Btw, this is on the 4-snake-screen-edge-issues branch. Lmk if I can provide additional info.

**Comment by amcrawford** [comment]
Resolved issue! Can restart game on click of "Start Game".

**Comment by stevekinney** [comment]
👍

**Comment by stevekinney** [comment]
I will look at this in the morning.

**Comment by amcrawford** [comment]
Oh, no worries!  I didn't realize it would re-notify you, no rush at all!

We're picking it up again tomorrow, too, but I made some notes on reopening the issue:

Can continuously play and restart game but, upon implementing scoring feature noticed bug in restart. I think the main issue is that we are not actually getting a new instance of the Snake in our startGame, but some more details here...

Behavior:  
- Can refresh page and start a game
- Score will increment to only "1" as a max
- Upon death, see alert and can click "Start Game" again to see newly rendered playing canvas
- _But_ in console see error: "Cannot read property '0' of undefined" within our pellet collision method

[Relevant Code](https://github.com/amcrawford/game-time/blob/4-snake-screen-edge-issues/lib/game.js)

The gameEnds() method currently reflects some attempts to hard-code a "refreshed" screen but, we believed that in calling startGame(), which uses a new instance of Snake, we would not be dealing with the old "snake" at all.  

Definitely some code to be cleaned up either way and we are thinking of moving more towards creating instances of the Game itself (esp. after watching the live-code of Space Invaders) but we still seemed to hit this issue so, if you see anything jump right out, it would be much appreciated! No rush, again, but thank you for the help!

**Comment by amcrawford** [comment]
Resolved again! We went the route of instantiating new instances of a game module and it all seems to be working on our new branch :+1:
