### ISSUE TITLE
localStorage is not saving the highest scores

### ISSUE THREAD

**Issue by sekharp** [amcrawford/game-time#33]

**Comment by sekharp** [comment]
@rrgayhart Hi Meeka! We are having an issue on our master branch where scores are saving to localstorage, but localstorage is not persisting after we refresh the page in the browser. Any idea what the issue is?

**Comment by rrgayhart** [comment]
Could potentially be this: http://stackoverflow.com/questions/7374355/localstorage-setitem-not-persisting-on-refresh

**Comment by rrgayhart** [comment]
Looks like there is some wonkiness with Chrome Dev Tools and potentially the local dev environment. I'd recommend deploying the app and seeing if it works in production.
